// <auto-generated />
using System;
using InvestLens.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestLens.DataAccess.Migrations
{
    [DbContext(typeof(InvestLensDataContext))]
    [Migration("20260503204637_RefactoringOfDatabase")]
    partial class RefactoringOfDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("InvestLens.Model.Entities.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentPortfolioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PortfolioType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentPortfolioId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("InvestLens.Model.Entities.Security", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("EmitentTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLoaded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IsTraded")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketpriceBoardid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryBoardid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("SecGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SecType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Securities");
                });

            modelBuilder.Entity("InvestLens.Model.Entities.Settings.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int?>("BoardEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardGroupId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "board_group_id");

                    b.Property<string>("BoardId")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "boardid");

                    b.Property<string>("BoardTitle")
                        .IsRequired()
                        .HasMaxLength(381)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "board_title");

                    b.Property<int>("EngineId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "engine_id");

                    b.Property<bool>("HasCandles")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "has_candles");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "is_primary");

                    b.Property<bool>("IsTraded")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "is_traded");

                    b.Property<int>("MarketId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "market_id");

                    b.HasKey("Id");

                    b.HasIndex("BoardEntityId");

                    b.HasIndex("BoardGroupId");

                    b.HasIndex("EngineId");

                    b.HasIndex("MarketId");

                    b.ToTable("Settings.Boards", (string)null);
                });

            modelBuilder.Entity("InvestLens.Model.Entities.Settings.BoardGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int?>("BoardGroupEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<int?>("EngineId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "is_default");

                    b.Property<bool>("IsOrderDriven")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "is_order_driven");

                    b.Property<bool>("IsTraded")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "is_traded");

                    b.Property<int>("MarketId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "market_id");

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "market_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(192)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<int>("TradeEngineId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "trade_engine_id");

                    b.Property<string>("TradeEngineName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "trade_engine_name");

                    b.Property<string>("TradeEngineTitle")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "trade_engine_title");

                    b.Property<int>("board_group_id")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "board_group_id");

                    b.HasKey("Id");

                    b.HasIndex("BoardGroupEntityId");

                    b.HasIndex("EngineId");

                    b.HasIndex("MarketId");

                    b.ToTable("Settings.BoardGroups", (string)null);
                });

            modelBuilder.Entity("InvestLens.Model.Entities.Settings.Duration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int?>("Days")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "days");

                    b.Property<int>("DurationCount")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "duration");

                    b.Property<string>("Hint")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "hint");

                    b.Property<int>("Interval")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "interval");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.HasKey("Id");

                    b.ToTable("Settings.Durations", (string)null);
                });

            modelBuilder.Entity("InvestLens.Model.Entities.Settings.Engine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.HasKey("Id");

                    b.ToTable("Settings.Engines", (string)null);
                });

            modelBuilder.Entity("InvestLens.Model.Entities.Settings.Market", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<bool>("HasCandles")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "has_candles");

                    b.Property<bool>("HasDelay")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "has_delay");

                    b.Property<bool>("HasExtraYields")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "has_extra_yields");

                    b.Property<bool>("HasHistory")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "has_history");

                    b.Property<bool>("HasHistoryFiles")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "has_history_files");

                    b.Property<bool>("HasHistoryTradesFiles")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "has_history_trades_files");

                    b.Property<bool>("HasOrderbook")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "has_orderbook");

                    b.Property<bool>("HasTrades")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "has_trades");

                    b.Property<bool>("HasTradingsession")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "has_tradingsession");

                    b.Property<bool>("IsOtc")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "is_otc");

                    b.Property<int?>("MarketEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarketId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "market_id");

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "market_name");

                    b.Property<string>("MarketPlace")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "marketplace");

                    b.Property<string>("MarketTitle")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "market_title");

                    b.Property<int>("TradeEngineId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "trade_engine_id");

                    b.Property<string>("TradeEngineName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "trade_engine_name");

                    b.Property<string>("TradeEngineTitle")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "trade_engine_title");

                    b.HasKey("Id");

                    b.HasIndex("MarketEntityId");

                    b.HasIndex("TradeEngineId");

                    b.ToTable("Settings.Markets", (string)null);
                });

            modelBuilder.Entity("InvestLens.Model.Entities.Settings.SecurityCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("SecurityGroupId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "security_group_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.HasKey("Id");

                    b.HasIndex("SecurityGroupId");

                    b.ToTable("Settings.SecurityCollections", (string)null);
                });

            modelBuilder.Entity("InvestLens.Model.Entities.Settings.SecurityGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "is_hidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(93)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.HasKey("Id");

                    b.ToTable("Settings.SecurityGroups", (string)null);
                });

            modelBuilder.Entity("InvestLens.Model.Entities.Settings.SecurityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("SecurityGroupName")
                        .IsRequired()
                        .HasMaxLength(93)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "security_group_name");

                    b.Property<string>("SecurityTypeName")
                        .IsRequired()
                        .HasMaxLength(93)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "security_type_name");

                    b.Property<string>("SecurityTypeTitle")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "security_type_title");

                    b.Property<string>("StockType")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "stock_type");

                    b.Property<int>("TradeEngineId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "trade_engine_id");

                    b.Property<string>("TradeEngineName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "trade_engine_name");

                    b.Property<string>("TradeEngineTitle")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "trade_engine_title");

                    b.HasKey("Id");

                    b.HasIndex("TradeEngineId");

                    b.ToTable("Settings.SecurityTypes", (string)null);
                });

            modelBuilder.Entity("InvestLens.Model.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("DoNotAdjustCash")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Event")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeeCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<decimal>("FeeTax")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NKD")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("InvestLens.Model.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InvestLens.Model.Entities.Portfolio", b =>
                {
                    b.HasOne("InvestLens.Model.Entities.User", "Owner")
                        .WithMany("Portfolios")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvestLens.Model.Entities.Portfolio", "ParentPortfolio")
                        .WithMany("ChildrenPortfolios")
                        .HasForeignKey("ParentPortfolioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");

                    b.Navigation("ParentPortfolio");
                });

            modelBuilder.Entity("InvestLens.Model.Entities.Settings.Board", b =>
                {
                    b.HasOne("InvestLens.Model.Entities.Settings.Board", "BoardEntity")
                        .WithMany()
                        .HasForeignKey("BoardEntityId");

                    b.HasOne("InvestLens.Model.Entities.Settings.BoardGroup", "BoardGroup")
                        .WithMany()
                        .HasForeignKey("BoardGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvestLens.Model.Entities.Settings.Engine", "Engine")
                        .WithMany()
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvestLens.Model.Entities.Settings.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardEntity");

                    b.Navigation("BoardGroup");

                    b.Navigation("Engine");

                    b.Navigation("Market");
                });

            modelBuilder.Entity("InvestLens.Model.Entities.Settings.BoardGroup", b =>
                {
                    b.HasOne("InvestLens.Model.Entities.Settings.BoardGroup", "BoardGroupEntity")
                        .WithMany()
                        .HasForeignKey("BoardGroupEntityId");

                    b.HasOne("InvestLens.Model.Entities.Settings.Engine", "Engine")
                        .WithMany()
                        .HasForeignKey("EngineId");

                    b.HasOne("InvestLens.Model.Entities.Settings.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardGroupEntity");

                    b.Navigation("Engine");

                    b.Navigation("Market");
                });

            modelBuilder.Entity("InvestLens.Model.Entities.Settings.Market", b =>
                {
                    b.HasOne("InvestLens.Model.Entities.Settings.Market", "MarketEntity")
                        .WithMany()
                        .HasForeignKey("MarketEntityId");

                    b.HasOne("InvestLens.Model.Entities.Settings.Engine", "TradeEngine")
                        .WithMany()
                        .HasForeignKey("TradeEngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketEntity");

                    b.Navigation("TradeEngine");
                });

            modelBuilder.Entity("InvestLens.Model.Entities.Settings.SecurityCollection", b =>
                {
                    b.HasOne("InvestLens.Model.Entities.Settings.SecurityGroup", "SecurityGroup")
                        .WithMany()
                        .HasForeignKey("SecurityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityGroup");
                });

            modelBuilder.Entity("InvestLens.Model.Entities.Settings.SecurityType", b =>
                {
                    b.HasOne("InvestLens.Model.Entities.Settings.Engine", "TradeEngine")
                        .WithMany()
                        .HasForeignKey("TradeEngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeEngine");
                });

            modelBuilder.Entity("InvestLens.Model.Entities.Transaction", b =>
                {
                    b.HasOne("InvestLens.Model.Entities.Portfolio", "Portfolio")
                        .WithMany("Transactions")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("InvestLens.Model.Entities.Portfolio", b =>
                {
                    b.Navigation("ChildrenPortfolios");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("InvestLens.Model.Entities.User", b =>
                {
                    b.Navigation("Portfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
